import { MD3LightTheme, MD3DarkTheme, configureFonts } from 'react-native-paper';

const fontConfig = {
    default: {
      displayLarge: { fontFamily: 'Rubik Mono One', fontWeight: '400' },
      displayMedium: { fontFamily: 'Rubik Mono One', fontWeight: '400' },
      displaySmall: { fontFamily: 'Rubik Mono One', fontWeight: '400' },
      headlineLarge: { fontFamily: 'Lexend Deca', fontWeight: '400' },
      headlineMedium: { fontFamily: 'Lexend Deca', fontWeight: '400' },
      headlineSmall: { fontFamily: 'Lexend Deca', fontWeight: '400' },
      bodyLarge: { fontFamily: 'Lexend Deca', fontWeight: '400' },
      bodyMedium: { fontFamily: 'Lexend Deca', fontWeight: '400' },
      bodySmall: { fontFamily: 'Lexend Deca', fontWeight: '400' },
      labelLarge: { fontFamily: 'Lexend Deca', fontWeight: '500' },
      labelMedium: { fontFamily: 'Lexend Deca', fontWeight: '500' },
      labelSmall: { fontFamily: 'Lexend Deca', fontWeight: '500' },
      titleLarge: { fontFamily: 'Lexend Deca', fontWeight: '400' },
      titleMedium: { fontFamily: 'Lexend Deca', fontWeight: '500' },
      titleSmall: { fontFamily: 'Lexend Deca', fontWeight: '500' },
    },
};

// LIGHT THEME
export const MorfilmLightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#206a4e',
    onPrimary: '#ffffff',
    primaryContainer: '#a9f2cd',
    onPrimaryContainer: '#002114',
    secondary: '#4d6357',
    onSecondary: '#ffffff',
    secondaryContainer: '#cfe9d9',
    onSecondaryContainer: '#0a1f16',
    tertiary: '#685f12',
    onTertiary: '#ffffff',
    tertiaryContainer: '#f1e48a',
    onTertiaryContainer: '#201c00',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#410002',
    background: '#f5fbf5',
    onBackground: '#171d1a',
    surface: '#f5fbf5',
    onSurface: '#171d1a',
    surfaceVariant: '#dbe5dd',
    onSurfaceVariant: '#404943',
    outline: '#707973',
    outlineVariant: '#bfc9c1',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#2c322e',
    inverseOnSurface: '#edf2ec',
    inversePrimary: '#8dd5b2',
    surfaceTint: '#206a4e',
  },
  fonts: configureFonts({ ...fontConfig, isV3: true }),
};

// DARK THEME
export const MorfilmDarkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#8dd5b2',
    onPrimary: '#003825',
    primaryContainer: '#005138',
    onPrimaryContainer: '#a9f2cd',
    secondary: '#b4ccbd',
    onSecondary: '#1f352a',
    secondaryContainer: '#354b40',
    onSecondaryContainer: '#cfe9d9',
    tertiary: '#d4c871',
    onTertiary: '#373100',
    tertiaryContainer: '#4f4700',
    onTertiaryContainer: '#f1e48a',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    background: '#0f1511',
    onBackground: '#dee4de',
    surface: '#0f1511',
    onSurface: '#dee4de',
    surfaceVariant: '#404943',
    onSurfaceVariant: '#bfc9c1',
    outline: '#8a938c',
    outlineVariant: '#404943',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#dee4de',
    inverseOnSurface: '#2c322e',
    inversePrimary: '#206a4e',
    surfaceTint: '#8dd5b2',
  },
  fonts: configureFonts({ ...fontConfig, isV3: true }),
};
